Repository alexweininger/recent-pdf, pull requests merged in 2018-10, with the labels that each got.

#11 Dev
  README.md
  js/load.js
  js/script.js
  src/browser_action/index.html
Labels: hacktoberfest

#12 Dev external css
  .gitignore
  .vscode/settings.json
  js/load.js
  manifest.json
  src/browser_action/browser_action.html
  src/browser_action/index.html
  src/browser_action/style.css
  test.txt
Labels: enhancement, hacktoberfest

#14 Fix URL display style
  js/script.js
  manifest.json
  src/browser_action/style.css
Labels: bug, good first issue, hacktoberfest, help wanted

#28 Update src/browser_action/style.css
  src/browser_action/style.css
Labels: enhancement, good first issue, hacktoberfest, help wanted

#29 reformatted list
  Contributors.md
Labels: enhancement, hacktoberfest

#30 Contributing readme section
  README.md
Labels: enhancement, good first issue, hacktoberfest, help wanted

#33 v1.0.0 official release
  content/promotional/v1.0.0/pr1400v2.png
  content/promotional/v1.0.0/pr920.png
  content/screenshots/v1.0.0/sct-280x1900_640x400.png
  content/screenshots/v1.0.0/sct-60x1900_640x400.png
  manifest.json
  ss.py
  versions/recent-pdf-1.0.0.zip
Labels: enhancement, hacktoberfest

#38 Added comments to script.js
  js/script.js
Labels: enhancement, hacktoberfest

#44 Dev
  .eslintrc.json
  .jshintrc
  js/script.js
Labels: hacktoberfest
