Repository alexweininger/recent-pdf, pull requests merged in 2019-10, with the labels that each got.

#61 Add npm/yarn watch to README
  README.md
Labels: Hacktoberfest

#65 fix security issues
  package-lock.json
Labels: Hacktoberfest, dependencies

#71 Update README.md
  README.md
Labels: Hacktoberfest

#77 Fix plural strings
  src/script.ts
Labels: Hacktoberfest, bug

#76 Fix file truncate for online pdfs
  src/script.ts
Labels: Hacktoberfest, bug

#74 Change directory to pdf name
  src/script.ts
Labels: Hacktoberfest, bug, linux

#78 Use window.browser instead of window.chrome
  src/options.ts
  src/script.ts
  src/web-ext/index.d.ts
Labels: Hacktoberfest, enhancement, good first issue

#83 Add setting for number of files to show in list (#81)
  dist/options/options.js
  src/script.ts
Labels: Hacktoberfest, enhancement

#85 Add semi colons
  src/script.ts
Labels: Hacktoberfest

#89 README.md Edits
  README.md
Labels: Hacktoberfest

#92 Dark Mode
  dist/index.html
  dist/options/options.js
  dist/style_dark_mode.css
  src/script.ts
Labels: Hacktoberfest
